[package]
name = "raccolta-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
raccolta-syntax = { path = "../raccolta-syntax" }

strum = { version = "*", features = [ "derive" ] }

[dev-dependencies]
pretty_assertions = "*"
rstest = "*"
