[package]
name = "raccolta-syntax"
version = "0.1.0"
edition = "2021"

[dependencies]
enum-fields = "*"
serde = { version = "*", features = [ "derive" ] }
strum = { version = "*", features = [ "derive" ] }
thiserror = "*"

[dev-dependencies]
pretty_assertions = "*"
rstest = "*"
